/** İl / ilçe listeleri — checkout ve adres formları ortak kullanır */

export const TURKIYE_CITIES = [
  "Adana",
  "Adıyaman",
  "Afyonkarahisar",
  "Ağrı",
  "Aksaray",
  "Amasya",
  "Ankara",
  "Antalya",
  "Ardahan",
  "Artvin",
  "Aydın",
  "Balıkesir",
  "Bartın",
  "Batman",
  "Bayburt",
  "Bilecik",
  "Bingöl",
  "Bitlis",
  "Bolu",
  "Burdur",
  "Bursa",
  "Çanakkale",
  "Çankırı",
  "Çorum",
  "Denizli",
  "Diyarbakır",
  "Düzce",
  "Edirne",
  "Elazığ",
  "Erzincan",
  "Erzurum",
  "Eskişehir",
  "Gaziantep",
  "Giresun",
  "Gümüşhane",
  "Hakkari",
  "Hatay",
  "Iğdır",
  "Isparta",
  "İstanbul",
  "İzmir",
  "Kahramanmaraş",
  "Karabük",
  "Karaman",
  "Kars",
  "Kastamonu",
  "Kayseri",
  "Kırıkkale",
  "Kırklareli",
  "Kırşehir",
  "Kilis",
  "Kocaeli",
  "Konya",
  "Kütahya",
  "Malatya",
  "Manisa",
  "Mardin",
  "Mersin",
  "Muğla",
  "Muş",
  "Nevşehir",
  "Niğde",
  "Ordu",
  "Osmaniye",
  "Rize",
  "Sakarya",
  "Samsun",
  "Şanlıurfa",
  "Siirt",
  "Sinop",
  "Şırnak",
  "Sivas",
  "Tekirdağ",
  "Tokat",
  "Trabzon",
  "Tunceli",
  "Uşak",
  "Van",
  "Yalova",
  "Yozgat",
  "Zonguldak",
] as const;

export const CITY_DISTRICTS: Record<string, string[]> = {
  İstanbul: [
    "Adalar",
    "Arnavutköy",
    "Ataşehir",
    "Avcılar",
    "Bağcılar",
    "Bahçelievler",
    "Bakırköy",
    "Başakşehir",
    "Bayrampaşa",
    "Beşiktaş",
    "Beykoz",
    "Beylikdüzü",
    "Beyoğlu",
    "Büyükçekmece",
    "Çatalca",
    "Çekmeköy",
    "Esenler",
    "Esenyurt",
    "Eyüpsultan",
    "Fatih",
    "Gaziosmanpaşa",
    "Güngören",
    "Kadıköy",
    "Kağıthane",
    "Kartal",
    "Küçükçekmece",
    "Maltepe",
    "Pendik",
    "Sancaktepe",
    "Sarıyer",
    "Silivri",
    "Şişli",
    "Sultanbeyli",
    "Sultangazi",
    "Tuzla",
    "Ümraniye",
    "Üsküdar",
    "Zeytinburnu",
  ],
  Ankara: ["Altındağ", "Çankaya", "Etimesgut", "Gölbaşı", "Keçiören", "Mamak", "Pursaklar", "Sincan", "Yenimahalle"],
  İzmir: [
    "Aliağa",
    "Balçova",
    "Bayraklı",
    "Bornova",
    "Buca",
    "Çiğli",
    "Gaziemir",
    "Güzelbahçe",
    "Karabağlar",
    "Karşıyaka",
    "Konak",
    "Menderes",
    "Menemen",
    "Narlıdere",
    "Seferihisar",
    "Torbalı",
    "Urla",
  ],
  Bursa: ["Gemlik", "Gürsu", "İnegöl", "Mudanya", "Nilüfer", "Osmangazi", "Yıldırım"],
  Antalya: ["Aksu", "Alanya", "Döşemealtı", "Kemer", "Kepez", "Konyaaltı", "Muratpaşa", "Serik"],
  Kocaeli: [
    "Başiskele",
    "Çayırova",
    "Darıca",
    "Derince",
    "Dilovası",
    "Gebze",
    "Gölcük",
    "İzmit",
    "Kandıra",
    "Karamürsel",
    "Kartepe",
    "Körfez",
  ],
  Adana: ["Çukurova", "Sarıçam", "Seyhan", "Yüreğir"],
  Konya: ["Karatay", "Meram", "Selçuklu"],
  Gaziantep: ["Şahinbey", "Şehitkamil"],
  Mersin: ["Akdeniz", "Erdemli", "Mezitli", "Tarsus", "Toroslar", "Yenişehir"],
};

export function getDistrictOptions(city: string): string[] {
  if (!city) return [];
  return CITY_DISTRICTS[city] ?? ["Merkez"];
}
